export default {
    data: vm => ({
      date: (new Date(Date.now() - (new Date()).getTimezoneOffset() * 60000)).toISOString().substr(0, 10),
      dataSaidaFormatada: vm.formatDate((new Date(Date.now() - (new Date()).getTimezoneOffset() * 60000)).toISOString().substr(0, 10)),
      
      retornoEmpresa: false,
      motivoSaida: false,
      dataSaida: false,
      retorno: null,
      hrRetorno: false,
      saida: null,
      hrSaida: false,
      select: null,

      
      funcionarios: [
        'Tobias Guimaraes',
        'Elisabete Ranciaro',
        'Josiane Oliveira Krainski',
        'Kezia de Lima Freitas',
        'Angela Maria Marcondes dos Santo',
        'Beatriz Graeser Macioski	2329	',
        'Come',
        'Danielle Cristine de Souza	2272	d',
        'Edilamar do Rocio Medeiros	3440	e',
        'Fabia Marques Costacurta Rodrigues	2262',
        'Gilvana Camila Pereira Machado	2258',
        'Gustavo Henrique Zoca	2',
        'Regiane Eveline de Brito	2266',
        'Joao Carlos Zanetti	',
        'Alejandro Pietry Ribeiro Trindade		al',
        'Alisson Couto	2',
        'Ana Maria Rolao Dos Santos Va',
        'Andre Luis Burei do Ca',
        'Bruno Noveli	3',
        'Caio Henrique Piantikovicz		c',
        'Caio L.K Schinemann	',
        'Charles Juan da Silva Mendes',
        'Daniele Harumi Ito Gemniczak		d',
        'Diego Liz Arraza',
        'Diogo Eduardo Dos Sant',
        'Fabio Bandacheski		fa',
        'Felipe Batista de Sou',
        'Fernando Rodnei Basilio		',
        'Henry Kocinba Tragante',
        'Joao Ricardo Cavali Ribei',
        'Josiane Almeida da Silv',
        'Kaique Spagnol Tofol',
        'Leandro Tagliari		',
        'Mayco Robson Da Silva Aoki Fonsec',
        'Murilo Augusto Horstmann Bispo		',
        'Priscila Barbosa Floriano		p',
        'Raissa da Silva Morgado',
        'Sidy Guedes',
        'Tobias Guimaraes	235	',
        'Ulisses Soares Maciel	23',
        'Wagner Dos Santos Goncalve',
        'William Camargo Martins Galdino	3444',
        'Adriano Rupprecht Zablonsky	35',
        'Anderson Pacheco1	32',
        'Barbara Hellen Da Conceicao	32',
        'Beatriz Babick',
        'Cesar Augusto Pitta Carvalho',
        'Daniel Soares Sil',
        'Debora Caroline Vilac',
        'Denilton Ely Moreira Macedo	',
        'Diogenes Bezerra da Silva',
        'Edson Fernand',
        'Emanuelle Gasparin	328',
        'Fernanda Demenjon Dos Santos	33',
        'Francisco Ferreira da Cunha	',
        'Juliana Venar Magalhaes	32',
        'Karen Estefani Romero Al',
        'Kauany Tonia',
        'Kelli Cristina da Si',
        'Maciel Tonetti',
        'Milena Gabardo da Si',
        'Milena Moraes Artigas',
        'Patricia Camargo Scorsin	3',
        'Pedro Co',
        'Rafael de Oliveira	',
        'Ricardo Vitor De Lima Sous',
        'Rogério Cordeiro Sobral',
        'Roseli Maria Orzechowski	325',
        'Silmara Aparecida Silv',
        'Tacito Luiz Cordeiro Galvao Filho	3',
        'Thiago Henrique Ferreira	',
        'Thiago Soares Da Silv',
        'Viviane Bueno Bedretchu',
        'Andre Luiz De Castro Al',
        'Aureo Hipolito',
        'Bianca Bagat',
        'Cassia Pagaes Schumanski	32',
        'Gregori Nabarros Ayre',
        'Ana Paula Da C',
        'Carolina Kortmann Osi',
        'Caroline Schons Sidronio	82',
        'Cassiano Martins	8',
        'Christine Luetke	8',
        'Danielle Pamela Dos Santos Rocha',
        'Delma Da Si',
        'Fernando Novak',
        'Glaucio da Silv',
        'Julio Matheus Von Paraski Navarro ',
        'Lucas Rogerio Prado Lo',
        'Pamela Menezes Szielasko	8',
        'Rafael Roberto Jungklaus	8',
        'Stefanny Greycy Da Ros',
        'Taciano Tavares	',
        'Vaness',
        'Andrielli Viegas Vargas	651	',
        'Edson dos Santos	',
        'Erick de Oliveira Nascimento	646	',
        'Patrick Barbieri Alves Ribeiro	647',
        'Aline Fagundes Thomas de So',
        'Cristopher George Abarca Padilla	334',
        'Elisabete Ranciar',
        'Evellyn Caroline Ganzert da Cunh',
        'Fatima Roden	3',
        'Giovana Luiza Tessari	32',
        'Graci Le',
        'Jose Augusto Menegon Cussoli',
        'Juliana De Andrade Carvalho Nascimento	3287	jul',
        'Juliano Garrett Galvao	3436	',
        'Lorena Moura Bellã',
        'Luciane dos Santos Ka',
        'Manoel Jose Vieira Net',
        'Marcia Regina da Sil',
        'Marcio Jose Mocelin',
        'Marta Corbetta Mazza	',
        'Monique de Almeida Santos',
        'Paola Batista de ',
        'Ronaldo Be',
        'Silvia Martins',
        'Ademir de Almeida Machado',
        'Alex Mor',
        'Alex Pav',
        'Aline Cristina da Conceicao	',
        'Alysson Grzybowski	380',
        'Amanda Louise Biazetto Pre',
        
      ],
     
    }),

    computed: {
      computedDateFormatted () {
        return this.formatDate(this.date)
      },
    },

    watch: {
      date () {
        this.dataSaidaFormatada = this.formatDate(this.date)
      },
    },

    methods: {
      formatDate (date) {
        if (!date) return null

        const [year, month, day] = date.split('-')
        return `${day}/${month}/${year}`
      },
      parseDate (date) {
        if (!date) return null

        const [month, day, year] = date.split('/')
        return `${day.padStart(2, '0')}-${month.padStart(2, '0')}-${year}`
      },
    },
  }